config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :users,only:[:show,:edit,:update]
 root 'layouts#top'
 get 'users' => 'users#index'
 get 'home/about' => 'layouts#about'
delete '/books' => 'books#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

   has_many  :books, dependent: :destroy

   validates :name, presence: true,length: {in: 2..20}
   validates :introduction,length: { maximum: 50}

   attachment :profile_image
 # deviseでemailを不必要にする
  def email_required?
   false
  end
  def email_changed?
   false
  end


end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_action :authenticate_user!
     #(ログインしていない状態で他のページに遷移しようとした場合、ログインページに繊維する)
     before_action :ensure_current_user, {only: [:edit,:update,:destroy]}
     #(ログインユーザー以外の情報を遷移しようとした時に制限をかける)



    def new
        @book = Book.new
    end



	def show
		@book = Book.new
        @user = User.find(params[:id])
        @books = @user.books

    end

    def new
        @user = User.new(user_params)
        if @user.save
         redirect_to  user_path(current_user.id)#成功の場合
        else
         render "users/sign_up"#失敗の場合
        end
    end

    def edit
        @user = User.find(params[:id])
    end

   




    def index
        @users =User.all
    	@books = Book.all
    	@book = Book.new
        @user = current_user
    end





    def update
        @user = User.find(params[:id])
       if  @user.update(user_params)
        flash[:notice] = "You have updated user successfully."

        redirect_to "/users/#{current_user.id}"
        else
        flash[:notice] = " errors prohibited this obj from being saved:"
            render :edit

       end
     end







   private
   

    def book_params
        params.require(:book).permit(:title, :body)
    end

    def user_params
        params.require(:user).permit(:name,:profile_image,:introduction)
    end

    def  ensure_current_user
        @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to user_path(current_user.id)

     end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <% if @user.errors %>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>

<div class="box">
<h2>User   info</h2>

<%= form_for(@user, url: user_path(current_user.id)) do |f| %>
    <h4>Name</h4>
    <%= f.text_field :name %>
    <h4>Image</h4>
  <%= f.attachment_field :profile_image %>
    <h4>introduction</h4>
      <%= f.text_area :introduction %>

    <%= f.submit 'Update User' %>

<% end %>

</div>

app/views/users/index.html.erb
<div class="box">


<div class= "col-xs-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>

  <h5>name</h5>
  <%= @user.name %>
  <h5>introduction</h5>
  <%= @user.introduction %>
  <%= link_to"",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>

       <!-- form_for部分 -->
  <%= form_for(@book,  url: books_path) do |f| %>


        <h2>New book</h2>
        <h4>Title</h4>
        <%= f.text_field :title,class: "col-xs-12" %>

        <h4>Opinion</h4>
        <%= f.text_field :body,class: "col-xs-12" %>
        <nav>

        <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
        </nav>
        <% end %>
  </div>

  <div class= "col-xs-9">
    <h2>Users</h2>
    <table class='table'>

    <% @users.each do |user| %>
    <tr>
    <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
   <th><%= user.name %><th>
   <th><%= link_to"Show",user_path(user.id) %></th>
   </tr>
   <% end %>
   </table>
  </div>

  </div>

app/views/users/show.html.erb
<div class="box">

  <div class= "col-xs-3">
    <h2>User info</h2>


    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
    <h5>name</h5>
    <%= @user.name %>
    <h5>introduction</h5>
    <%= @user.introduction %>
    <%= link_to"",edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>








        <!-- form_for部分 -->
    <%= form_for(@book,  url: books_path) do |f| %>
    <h2>New book</h2>
    <h4>Title</h4>
    <%= f.text_field :title,class: "col-xs-12" %>
    <h4>Opinipn</h4>
    <%= f.text_field :body,class: "col-xs-12" %>
    <nav>
        <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    </nav>
    <% end %>

  </div>







  <div class= "col-xs-9">
   <h2>Books</h2>
   <table class='table table-hover table-inverse'>

   <tr>
     <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th colspan="3"></th>
   </tr>

   <% @books.each do |book| %>
  <%= link_to user_path(@user.id) do %>
   <tr>
   <td><%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
   <% end %>
   <td><%=link_to book.title, book_path(book.id)%></td>
   <td><%= book.body %></td>
   </tr>
   <% end %>
   </table>

  </div>
</div>