config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :users,only:[:show,:edit,:update]
 root 'layouts#top'
 get 'users' => 'users#index'
 get 'home/about' => 'layouts#about'
delete '/books' => 'books#destroy'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true,
	                 length: { maximum: 200}
	                 
	                 
	                 

	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
     before_action :authenticate_user!
     before_action :ensure_current_user, {only: [:edit,:update,:destroy]}
     #(ログインユーザー以外の人が情報を遷移しようとした時に制限をかける)

	def create
        @user = current_user
		@book = Book.new(book_params)
        @book.user_id = (current_user.id)
	    if @book.save
        flash[:notice] = "You have creatad book successfully."
		redirect_to  book_path(@book.id)
        # redirect_to "/books/#{@book.id}"

        else
        @books = Book.all
        flash[:notice] = ' errors prohibited this obj from being saved:'
        render "index"
        end
	end

    def show
        @user = current_user
    	@book = Book.find(params[:id])
    	@book_new = Book.new
    end

    def index
        @user = current_user
        @books = Book.all
        @book = Book.new
    end

    def edit
    	@book = Book.find(params[:id])
    end


    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
        flash[:notice] = "You have creatad book successfully."
        redirect_to  book_path(@book.id)

        else
        @books = Book.all
         flash[:notice]= ' errors prohibited this obj from being saved:'
        render "edit"
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to "/books"
     end

	private

    def book_params
        params.require(:book).permit(:title, :body)
    end

     def user_params
        params.require(:user).permit(:name,:profile_image,:introduction)
   end

     def  ensure_current_user
      @book = Book.find(params[:id])
     if @book.user_id != current_user.id
        redirect_to books_path
     end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="box2">

<h1>Editing Book</h1>
<%= form_for(@book, url: book_path(@book.id)) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title,class:"col-xs-12" %>
    <h4>Opinion</h4>

    <%= f.text_area :body,class:"col-xs-12" %>

  <nav>
     <%= f.submit 'Update Book',class: "col-xs-12 btn btn-primary" %>
  </nav>
　<% end %>

<%= link_to "show",book_path(@book.id)%>
<%= link_to "Back",books_path %>

</div>

app/views/books/index.html.erb
 <% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>


<div class="box">

 <div class= "col-xs-3">
   <h2>User info</h2>

   <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %>
    <%= link_to"",edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>







        <!-- form_for部分 -->
   <%= form_for(@book,  url: books_path) do |f| %>
    <h2>New book</h2>
    <h4>Title</h4>
    <%= f.text_field :title,class: "col-xs-12" %>

    <h4>Opinion</h4>
     <%= f.text_field :body,class: "col-xs-12" %>
    <nav>
    <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    </nav>
    <% end %>

  </div>





    <div class= "col-xs-9">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>

      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      </tr>





      <% @books.each do |book| %>
      <tr>
      <td><%= link_to user_path(book.user_id) do %>
      <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
      <% end %>

      <td><%=link_to book.title, book_path(book.id)%></td>
      <td><%=link_to book.body %></td>
      </tr>
      <% end %>
      </table>
    </div>

</div>

app/views/books/show.html.erb
<div class="box">
<% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>

 <div class= "col-xs-3">
  <h2>User info</h2>
   <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>

   <h5>name</h5>
   <%= @book.user.name %>
   <h5>introduction</h5>
   <%= @book.user.introduction %>

   <%= link_to"",edit_user_path(@book.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>





        <!-- form_for部分 -->
   <%= form_for(@book_new,  url: books_path)  do |f| %>


    <h2>New book</h2>
    <h4>Title</h4>
     <%= f.text_field :title,class: "col-xs-12" %>
    <h4>Opinion</h4>
    <%= f.text_field :body,class: "col-xs-12" %>
    <nav>
     <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    </nav>
    <% end %>
  </div>




  <div class= "col-xs-9">
    <h2>Book detail</h2>
    <table class='table' >
    <tr>
    <td>
      <%= link_to user_path(@book.user_id) do %>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:'50x50',format: 'no_image.jpg' %>
         <nav>
           <%= @book.user.name %>
         </nav>
       <% end %>
    </td>
    


    <td><%= link_to @book.title %></td>
    <td><%= @book.body %></td>
    <% if @book.user_id == current_user.id %>
    <td><%= link_to"edit", edit_book_path(@book.id),class:"btn-sm btn-success" %></td>
    <td><%= link_to "destroy", book_path(@book.id), class:"btn-sm btn-danger destroy(@book.id)", method: :delete,data: {confirm: "削除しますか？"} %></td>
    <% end %>
    </tr>
    </table>
  </div>
</div>