config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :users,only:[:show,:edit,:update]
 root 'layouts#top'
 get 'users' => 'users#index'
 get 'home/about' => 'layouts#about'
delete '/books' => 'books#destroy'
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
	def top
	end
	def about
	end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/about.html.erb
<div class="box">
<title>Bookers2</title>

<h1>Welcome to<span class='glyphicon glyphicon-book'></span><strong>Bookers!</strong></h1>

</div>

app/views/layouts/application.html.erb
<div class="box">


<!DOCTYPE html>
<html>
<head>
<title>Bookers2</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>











<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class='nav navbar-nav navbar-left' >
        <div class="b">Bookers2</div>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Home", user_path(current_user.id),class:"glyphicon glyphicon-home" %></a></li>
            <li><%= link_to "Users", "/users",class:"glyphicon glyphicon-user" %></a></li>
            <li><%= link_to "Books", "/books",class:"glyphicon glyphicon-book" %></a></li>
            <li><%= link_to "log out", destroy_user_session_path,class:" glyphicon  glyphicon-log-out",method: :delete %></li>

          <% else %>
            <li><%= link_to"Home",root_path,  class:"glyphicon glyphicon-home" %></li>
            <li><%= link_to"About",home_about_path,class:"glyphicon glyphicon-link" %></li>
            <li><%= link_to"Sign up", "/users/sign_up",class:"glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to"login", "/users/sign_in",  class:"glyphicon glyphicon-log-in" %></li>
          <% end %>
        </<ul>
      </nav>
    </div>
  </header>

  <div class= "body">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
  </div>

 <%= yield %>


  <footer>
    <div class='container'>
      <div class='row'>
        <div class='col-xs-3 col-xs-offset-9'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/layouts/top.html.erb
<div class="box">

<head>
    <title>Bookers2</title>
</head>




<div class='body'>
  <div class='container'>
<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
<h1>welcome to<span class='glyphicon glyphicon-book'></span>Bookers !!</h1>

<p>In<span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about varioius books!</p>


  <div class="btn-wrapper">
      <div class="row">
      <div>
  <div class="btn-wrapper">
      <div class="row">
      <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
    </div>
      <div class="row">
      <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
     </div>
   </div>
 </div>
 </div>

  </body>


  </div>